import { useEffect, useMemo, useState } from "react";
import {
  ArrowLeft, ArrowRight, Boat, CalendarBlank, Check, CheckCircle, Clock,
  CreditCard, List, MapPin, Minus, Plus, ShieldCheck, Sparkle, Users,
  Warning, Wrench, X,
} from "@phosphor-icons/react";
import "@fontsource/cormorant-garamond/400.css";
import "@fontsource/cormorant-garamond/500.css";
import "@fontsource/cormorant-garamond/600.css";
import "@fontsource/manrope/400.css";
import "@fontsource/manrope/500.css";
import "@fontsource/manrope/600.css";
import "@fontsource/manrope/700.css";
import { boats, dateOptions, durations, initialBlocks, initialBookings, instructors, shifts } from "./data";
import { allocateBooking, formatPrice, getAvailableSlots, toMinutes, validateReassignment } from "./availability";

const shortDates = {
  "2026-08-23": "23 августа", "2026-08-24": "24 августа",
  "2026-08-25": "25 августа", "2026-09-05": "5 сентября",
};

function Header({ view, onView, onBook }) {
  const [menuOpen, setMenuOpen] = useState(false);
  return <header className={`site-header ${view !== "home" ? "site-header--solid" : ""}`}>
    <button className="wordmark" onClick={() => onView("home")} aria-label="На главную">NEVA</button>
    <nav className={menuOpen ? "nav nav--open" : "nav"} aria-label="Основная навигация">
      <button onClick={() => onView("home", "how")}>Как это работает</button>
      <button onClick={() => onView("home", "fleet")}>Флот</button>
      <button onClick={() => onView("home", "pier")}>Причал</button>
      <button onClick={() => onView("home", "faq")}>FAQ</button>
      <button className={view === "case" ? "active" : ""} onClick={() => onView("case")}>Продуктовый кейс</button>
      <button className={view === "admin" ? "active" : ""} onClick={() => onView("admin")}>Админка</button>
    </nav>
    <button className="header-cta" onClick={onBook}>Посмотреть свободное время</button>
    <button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Открыть меню">{menuOpen ? <X size={24}/> : <List size={24}/>}</button>
  </header>;
}

function Stepper({ value, onChange, min = 1, max = 8 }) {
  return <div className="stepper">
    <button onClick={() => onChange(Math.max(min, value - 1))} disabled={value <= min} aria-label="Уменьшить"><Minus size={18}/></button>
    <strong>{value}</strong>
    <button onClick={() => onChange(Math.min(max, value + 1))} disabled={value >= max} aria-label="Увеличить"><Plus size={18}/></button>
  </div>;
}

function HeroBooking({ bookingDraft, setBookingDraft, bookings, blocks, onStart }) {
  const slots = useMemo(() => getAvailableSlots({ ...bookingDraft, bookings, blocks }), [bookingDraft, bookings, blocks]);
  const compactSlots = slots.filter((slot) => slot.available).slice(0, 8);
  return <div className="hero-booking" aria-label="Быстрый поиск свободного времени">
    <div className="field-group field-group--passengers"><label>Пассажиры</label><Stepper value={bookingDraft.passengers} onChange={(passengers) => setBookingDraft((draft) => ({ ...draft, passengers }))}/><small>1–8 человек · Demo</small></div>
    <label className="field-group"><span>Дата</span><select value={bookingDraft.date} onChange={(event) => setBookingDraft((draft) => ({ ...draft, date: event.target.value }))}>{dateOptions.map((date) => <option key={date.value} value={date.value}>{date.label}</option>)}</select></label>
    <div className="field-group field-group--wide"><label>Продолжительность</label><div className="duration-row">{durations.map((duration) => <button key={duration} className={bookingDraft.duration === duration ? "selected" : ""} onClick={() => setBookingDraft((draft) => ({ ...draft, duration }))}>{duration} {duration === 1 ? "час" : "часа"}{duration === 2 && <em>популярно</em>}</button>)}</div></div>
    <div className="field-group field-group--wide"><label>Выберите время</label><div className="slot-preview">{compactSlots.length ? compactSlots.map((slot) => <button key={slot.time} className={bookingDraft.start === slot.time ? "selected" : ""} onClick={() => setBookingDraft((draft) => ({ ...draft, start: slot.time }))}>{slot.time}</button>) : <span className="no-slots">На эту дату нет подходящих вариантов</span>}</div></div>
    <button className="primary-button hero-booking__submit" onClick={onStart} disabled={!compactSlots.length}>Найти время <ArrowRight size={20}/></button>
    <p className="allocation-note"><ShieldCheck size={17}/> Подходящий катер назначим автоматически</p>
  </div>;
}

function BookingFlow({ draft, setDraft, bookings, blocks, onClose, onConfirm }) {
  const [step, setStep] = useState(1);
  const [name, setName] = useState("");
  const [phone, setPhone] = useState("");
  const [seconds, setSeconds] = useState(600);
  const [paymentLoading, setPaymentLoading] = useState(false);
  const slots = useMemo(() => getAvailableSlots({ ...draft, bookings, blocks }), [draft, bookings, blocks]);
  const availableSlots = slots.filter((slot) => slot.available);
  const allocation = draft.start ? allocateBooking({ ...draft, bookings, blocks }) : null;
  useEffect(() => { if (step !== 4) return; const timer = window.setInterval(() => setSeconds((value) => Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer); }, [step]);
  useEffect(() => { if (seconds === 0 && step === 4) setStep(2); }, [seconds, step]);
  const completePayment = () => { setPaymentLoading(true); window.setTimeout(() => { onConfirm({ ...draft, name, phone, allocation }); setPaymentLoading(false); setStep(5); }, 1100); };
  return <div className="booking-overlay" role="dialog" aria-modal="true" aria-label="Оформление бронирования"><div className="booking-modal">
    <div className="booking-modal__top"><button onClick={step > 1 && step < 5 ? () => setStep(step - 1) : onClose} aria-label="Назад">{step > 1 && step < 5 ? <ArrowLeft size={22}/> : <X size={22}/>}</button><div className="flow-progress">{[1,2,3,4].map((item) => <span key={item} className={step >= item ? "active" : ""}/>)}</div><span className="flow-step">{step < 5 ? `${step}/4` : "Готово"}</span></div>
    {step === 1 && <div className="flow-screen"><p className="eyebrow">Бронирование онлайн</p><h2>Расскажите о поездке</h2><p className="flow-lead">Покажем только те варианты, которые действительно можно забронировать.</p>
      <div className="flow-form-row"><div><label>Сколько вас будет?</label><p>Учитывайте всех пассажиров, включая детей.</p></div><Stepper value={draft.passengers} onChange={(passengers) => setDraft({ ...draft, passengers })}/></div>
      <label className="flow-field"><span>Дата</span><select value={draft.date} onChange={(event) => setDraft({ ...draft, date: event.target.value, start: "" })}>{dateOptions.map((date) => <option key={date.value} value={date.value}>{date.label}</option>)}</select></label>
      <div className="flow-field"><span>На сколько часов?</span><div className="duration-cards">{durations.map((duration) => <button key={duration} className={draft.duration === duration ? "selected" : ""} onClick={() => setDraft({ ...draft, duration, start: "" })}><strong>{duration} {duration === 1 ? "час" : "часа"}</strong><span>{formatPrice(duration)}</span>{duration === 2 && <em>Популярный вариант</em>}</button>)}</div></div>
      <div className="flow-info"><Boat size={20}/> Конкретный катер выбирать не нужно — подберём минимально подходящий.</div><button className="primary-button flow-next" onClick={() => setStep(2)}>Показать свободное время <ArrowRight/></button>
    </div>}
    {step === 2 && <div className="flow-screen"><p className="eyebrow">{dateOptions.find((date) => date.value === draft.date)?.label}</p><h2>Выберите время</h2><p className="flow-lead">Начало с шагом 30 минут. Буферы, смены и занятость ресурсов уже учтены.</p><div className="commerce-slots">{slots.map((slot) => <button key={slot.time} disabled={!slot.available} className={draft.start === slot.time ? "selected" : ""} title={slot.reason || "Доступно"} onClick={() => setDraft({ ...draft, start: slot.time })}><strong>{slot.time}</strong><span>{draft.duration} {draft.duration === 1 ? "час" : "часа"}</span><b>{formatPrice(draft.duration)}</b></button>)}</div>{!availableSlots.length && <div className="empty-state"><CalendarBlank size={30}/> Попробуйте другую дату или длительность.</div>}<button className="primary-button flow-next" disabled={!draft.start || !allocation?.available} onClick={() => setStep(3)}>Продолжить <ArrowRight/></button></div>}
    {step === 3 && <div className="flow-screen"><p className="eyebrow">Оформление</p><h2>Проверьте детали</h2><div className="booking-summary"><div><span>Дата</span><strong>{shortDates[draft.date]}</strong></div><div><span>Время</span><strong>{draft.start} · {draft.duration} ч</strong></div><div><span>Пассажиры</span><strong>{draft.passengers}</strong></div><div><span>Полная стоимость</span><strong>{formatPrice(draft.duration)}</strong></div><div><span>Предоплата</span><strong>Demo: {formatPrice(draft.duration * .25)}</strong></div><div><span>Остаток перед выходом</span><strong>{formatPrice(draft.duration * .75)}</strong></div></div><p className="tbd-note"><Warning size={18}/> Размер предоплаты требует согласования с бизнесом.</p><label className="flow-field"><span>Имя</span><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Как к вам обращаться"/></label><label className="flow-field"><span>Телефон</span><input value={phone} onChange={(e) => setPhone(e.target.value)} placeholder="+7 ___ ___-__-__" inputMode="tel"/></label><p className="document-note">Документ совершеннолетнего участника понадобится перед выходом. Паспортные данные онлайн не нужны.</p><button className="primary-button flow-next" disabled={!name.trim() || phone.replace(/\D/g, "").length < 10} onClick={() => setStep(4)}>Внести предоплату <CreditCard/></button></div>}
    {step === 4 && <div className="flow-screen payment-screen"><div className="hold-orb"><Clock size={34}/></div><p className="eyebrow">Hold · Demo</p><h2>Слот временно закреплён за вами</h2><p className="hold-timer">{String(Math.floor(seconds/60)).padStart(2,"0")}:{String(seconds%60).padStart(2,"0")}</p><p className="flow-lead">Повторная проверка пройдена. После demo-оплаты бронь станет подтверждённой.</p><div className="mock-card"><span>Безопасная demo-оплата</span><strong>{formatPrice(draft.duration*.25)}</strong><div>•••• •••• •••• 4242</div></div><button className={`primary-button flow-next ${paymentLoading ? "loading" : ""}`} onClick={completePayment} disabled={paymentLoading}>{paymentLoading ? "Подтверждаем…" : "Оплатить и подтвердить"} <Check/></button><button className="text-button" onClick={() => { setSeconds(0); setStep(2); }}>Смоделировать неуспешную оплату</button></div>}
    {step === 5 && <div className="flow-screen success-screen"><div className="success-mark"><Check size={40} weight="bold"/></div><p className="eyebrow">NV-2047</p><h2>Бронь подтверждена</h2><p className="flow-lead">Поездка добавлена в единое расписание. Ничего дополнительно подтверждать не нужно.</p><div className="success-ticket"><div><CalendarBlank/><span>{shortDates[draft.date]} · {draft.start}</span></div><div><Clock/><span>{draft.duration} ч · {formatPrice(draft.duration)}</span></div><div><Users/><span>{draft.passengers} пассажиров</span></div><div><MapPin/><span>Причал в центре Петербурга</span></div><div><Boat/><span>{allocation?.boat?.name} · назначен автоматически</span></div><div><ShieldCheck/><span>{allocation?.instructor ? `Инструктор ${allocation.instructor.name}` : "Инструктор будет назначен при составлении смен"}</span></div></div><p className="weather-note">Если погодные условия не позволят выйти на воду, мы свяжемся с вами и согласуем перенос.</p><button className="primary-button flow-next" onClick={onClose}>Вернуться на главную</button></div>}
  </div></div>;
}

function HomePage({ draft, setDraft, bookings, blocks, onBook }) {
  const nextSlots = useMemo(() => getAvailableSlots({ ...draft, date: "2026-08-24", bookings, blocks }).filter((slot) => slot.available).slice(0,4), [draft, bookings, blocks]);
  return <main className="home-page">
    <section className="hero"><img src="/assets/hero-neva-evening.png" alt="Катер с парой на Неве в вечернем Петербурге"/><div className="hero-shade"/><div className="hero-copy"><h1>Ваши два<br/>часа на воде</h1><p>Катер в Петербурге — без прав<br/>и лишних звонков</p><div><strong>6 000 ₽ / час</strong><span>· инструктор включён</span></div></div><HeroBooking bookingDraft={draft} setBookingDraft={setDraft} bookings={bookings} blocks={blocks} onStart={onBook}/><button className="mobile-hero-cta" onClick={onBook}>Посмотреть свободное время <ArrowRight/></button></section>
    <section className="section intro-section" id="how"><div className="section-heading"><p className="eyebrow">Лёгкая аренда, яркие впечатления</p><h2>Вы отдыхаете — мы берём на себя всё остальное</h2></div><div className="how-grid">{[["01","Выберите поездку","Укажите количество гостей, дату и длительность."],["02","Забронируйте онлайн","Покажем только реально доступное время и закрепим слот."],["03","Приезжайте к причалу","Покажите документ, оплатите остаток и выходите на воду."]].map(([number,title,text]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="section experience-section"><div className="experience-image"><img src="/assets/lifestyle-friends-neva.png" alt="Компания друзей на прогулке по Неве"/></div><div className="experience-copy"><p className="eyebrow">Петербург с воды</p><h2>Повод может быть любым. Впечатление — одно.</h2><p>Свидание, день рождения, девичник или спонтанная прогулка с друзьями. Вы выбираете время, а система — подходящий катер.</p><div className="occasion-list">{["Свидание","С друзьями","День рождения","Девичник","Для туристов"].map((item) => <span key={item}>{item}</span>)}</div></div></section>
    <section className="section slots-section"><div className="section-heading section-heading--row"><div><p className="eyebrow">Ближайшие варианты</p><h2>Свободное время на завтра</h2></div><p>Для {draft.passengers} гостей · {draft.duration} часа</p></div><div className="public-slots">{nextSlots.map((slot,index) => <button key={slot.time} className={index===1?"is-hovered":""} onClick={() => { setDraft({...draft,date:"2026-08-24",start:slot.time}); onBook(); }}><strong>{slot.time}</strong><span>{draft.duration} часа</span><b>{formatPrice(draft.duration)}</b><ArrowRight/></button>)}</div><p className="slots-caption"><Sparkle size={18}/> Катер и инструктор уже учтены. Никаких звонков для подтверждения.</p></section>
    <section className="section fleet-section" id="fleet"><div className="fleet-copy"><p className="eyebrow">Наш флот</p><h2>Не каталог. Подходящий катер — без лишнего выбора.</h2><p>Катера похожи внешне и отличаются прежде всего вместимостью. Мы автоматически назначаем самый маленький подходящий вариант, чтобы сохранять большие катера для больших компаний.</p><div className="fleet-pills">{boats.map((boat) => <span key={boat.id}>{boat.name} · до {boat.capacity} гостей <small>Demo</small></span>)}</div><p className="tbd-inline">Фактическая вместимость уточняется по документам до production launch.</p></div><img src="/assets/boat-interior-detail.png" alt="Премиальный интерьер катера"/></section>
    <section className="section benefits-section">{[[ShieldCheck,"Права не нужны","Всю поездку группу сопровождает инструктор."],[CreditCard,"Без залога","6 000 ₽ в час — полная обязательная цена."],[CalendarBlank,"Онлайн-бронирование","Свободное время видно сразу, без переписки."],[MapPin,"Один причал","Точную точку старта пришлём после бронирования."]].map(([Icon,title,text]) => <article key={title}><Icon size={28}/><h3>{title}</h3><p>{text}</p></article>)}</section>
    <section className="section pier-section" id="pier"><div className="pier-card"><p className="eyebrow">Точка старта</p><h2>Причал в центре Петербурга</h2><p>Удобная точка рядом с набережной. Точный адрес и памятка придут после подтверждения брони.</p><div className="map-lines"><span/><span/><span/><i><MapPin size={26}/></i></div></div><div className="price-card"><p className="eyebrow">Прозрачная цена</p><strong>6 000 ₽</strong><span>за 1 час · инструктор включён</span><hr/><p>1 час — 6 000 ₽</p><p>2 часа — 12 000 ₽</p><p>3 часа — 18 000 ₽</p><p>4 часа — 24 000 ₽</p></div></section>
    <section className="section faq-section" id="faq"><div><p className="eyebrow">Коротко о важном</p><h2>Частые вопросы</h2></div><div className="faq-list">{[["Нужны ли права?","Нет. Инструктор сопровождает вашу группу на протяжении всей аренды."],["Дети считаются пассажирами?","Да. Дети учитываются в общей вместимости и могут участвовать вместе со взрослыми."],["Нужно ли загружать паспорт?","Нет. Документ совершеннолетнего участника понадобится только перед выходом."],["Что будет при плохой погоде?","Мы свяжемся с вами и согласуем перенос. Формальная политика ещё требует согласования."]].map(([q,a]) => <details key={q}><summary>{q}<Plus/></summary><p>{a}</p></details>)}</div></section>
    <section className="final-cta"><p className="eyebrow">Петербург ждёт</p><h2>Выберите свой час на воде</h2><p>Свободные слоты — без звонков и ожидания.</p><button className="light-button" onClick={onBook}>Посмотреть свободное время <ArrowRight/></button></section>
  </main>;
}

function Journey({ current = false }) {
  const items = current ? ["Реклама / сарафан","Сообщение","Ожидание","Ручная проверка","Согласование","Оплата у причала","Аренда"] : ["Сайт","Пассажиры и дата","Расчёт availability","Слот","Предоплата","Confirmed","Единое расписание"];
  return <div className="journey">{items.map((item,index) => <div key={item}><span>{index+1}</span><p>{item}</p>{index<items.length-1&&<ArrowRight/>}</div>)}</div>;
}

function CasePage({ onView }) {
  return <main className="case-page">
    <section className="case-hero"><p className="eyebrow">Product Manager case · 2026</p><h1>Из ручной проверки —<br/>в подтверждённую бронь</h1><p>Как интервью превратило запрос «сделать сайт» в resource-based booking system, которая повышает конверсию и снижает простои.</p><div><button className="primary-button" onClick={() => onView("home")}>Открыть клиентский сайт</button><button className="secondary-button" onClick={() => onView("admin")}>Посмотреть админку</button></div></section>
    <section className="case-section case-context"><div><p className="case-index">01 — Context</p><h2>Не «сделать сайт», а увеличить подтверждённые часы аренды</h2></div><div className="context-grid"><article><strong>3</strong><span>катера</span></article><article><strong>2</strong><span>инструктора</span></article><article><strong>≈9</strong><span>оплаченных катеро-часов в хороший день — приблизительный baseline</span></article><article><strong>120 000 ₽</strong><span>обслуживание флота в месяц, без полной unit economics</span></article></div></section>
    <section className="case-section"><p className="case-index">02 — Discovery</p><div className="case-two-col"><div><h2>Что выяснилось за первоначальным запросом</h2><p>Клиент выбирает не катер, а поездку для своей компании. Флот отличается вместимостью, а каждый выход требует инструктора на всё время аренды.</p></div><ul className="insight-list"><li>График смен известен примерно на неделю</li><li>Катера могут быть закрыты на обслуживание</li><li>После аренды нужен 30-минутный буфер</li><li>Дальние брони подтверждаются до назначения инструктора</li><li>Все каналы пишут в одно расписание</li></ul></div></section>
    <section className="case-section journeys"><p className="case-index">03 — Journey</p><h2>Ручная проверка исчезает из happy path</h2><h3>Сейчас</h3><Journey current/><h3>После MVP</h3><Journey/></section>
    <section className="case-insight"><p className="case-index">04 — Key insight</p><h2>3 катера ≠ 3 параллельные аренды</h2><p>Свободный катер не означает доступный слот. Реальная capacity определяется минимальным доступным сочетанием Boat × Instructor с учётом смен, блокировок и буферов.</p><div className="resource-demo"><div><span>10:00–12:00</span><strong>Катер A</strong><b>Алексей · занят</b></div><div><span>10:00–12:00</span><strong>Катер B</strong><b>Михаил · занят</b></div><div className="muted"><span>10:00–12:00</span><strong>Катер C</strong><b>Физически свободен · слот недоступен</b></div></div></section>
    <section className="case-section"><p className="case-index">05 — Product goal</p><blockquote>Увеличить количество подтверждённых бронирований и загрузку бизнеса за счёт self-service бронирования, одновременно сократив ручную работу владелицы и исключив конфликты ресурсов.</blockquote><div className="acquisition"><article><h3>Acquisition</h3><p>Сарафан, VK, реклама у причала и туристический спрос приводят клиентов.</p></article><article><h3>Conversion & Operations</h3><p>Сайт улучшает превращение спроса в бронь и работу расписания, но сам по себе не гарантирует новый трафик.</p></article></div></section>
    <section className="case-section"><p className="case-index">06 — Users & JTBD</p><div className="role-grid">{[["Клиент","Быстро увидеть реальное свободное время и забронировать без звонков."],["Ирина","Получить единое расписание с автоматической проверкой ресурсов."],["Инструктор","Видеть актуальное read-only расписание поездок."]].map(([role,job]) => <article key={role}><span>{role}</span><p>«{job}»</p></article>)}</div></section>
    <section className="case-section"><p className="case-index">07 — Availability logic</p><h2>Сложность скрыта системой</h2><div className="logic-flow">{["Пассажиры","Подходящий катер","Блокировки и брони","Инструктор на смене","30 мин буфера","Lead time 1 час","Доступный слот"].map((item,i) => <div key={item}><span>{i+1}</span><strong>{item}</strong>{i<6&&<ArrowRight/>}</div>)}</div><p className="logic-note">Если смен ещё нет, подтверждённая бронь создаёт staffing commitment вместо неподтверждённой заявки.</p></section>
    <section className="case-section mvp-section"><p className="case-index">08 — Scope</p><div className="mvp-columns"><div><h2>MVP</h2><ul><li>Клиентский booking flow и partial prepayment</li><li>Availability engine и Hold</li><li>Единый календарь online/offline</li><li>Автоназначение минимального катера</li><li>Смены, блокировки, ручная бронь</li><li>Staffing commitments</li><li>Read-only расписание инструктора</li></ul></div><div><h2>Later</h2><ul><li>Личный кабинет и приложение</li><li>Лояльность и промокоды</li><li>Dynamic pricing</li><li>Чат, отзывы и маршруты</li><li>Расширенная CRM и BI</li></ul></div></div></section>
    <section className="case-section"><p className="case-index">09 — Edge cases</p><div className="edge-grid">{["Нет инструктора — слот скрыт","Инструктор вне смены — недоступен","Техблок исключает катер","4 часа + 30 минут проверяются целиком","Failed payment снимает Hold","Ручная бронь меняет online availability","Дальняя бронь confirmed с instructor TBD","Плохая погода → предложить перенос"].map((edge) => <span key={edge}><CheckCircle size={20}/>{edge}</span>)}</div></section>
    <section className="case-section metrics"><p className="case-index">10 — Metrics & hypotheses</p><h2>Успех — это не посещаемость</h2><div className="metric-primary"><span>Primary metric</span><strong>Confirmed rental hours / day</strong><p>Эффективная capacity считается по реально доступным сочетаниям Boat × Instructor, а не 3 × 12 часов.</p></div><div className="metric-grid">{["Booking conversion","Self-service rate","Payment completion","Manual requests","Cancellation rate","Average duration","Utilization by boat","Booking conflicts → 0"].map((metric) => <span key={metric}>{metric}</span>)}</div><div className="hypotheses"><p>H1 · Self-service availability повысит conversion.</p><p>H2 · Единое расписание приблизит conflicts к нулю.</p><p>H3 · Минимальный подходящий катер сохранит capacity для больших групп.</p><p>H4 · Staffing commitments позволят принимать дальние брони без потерь.</p></div></section>
    <section className="case-section questions"><p className="case-index">11 — TBD before production</p><h2>Known facts ≠ assumptions</h2><ol><li>Точная вместимость каждого катера</li><li>Размер частичной предоплаты</li><li>Cancellation и refund policy</li><li>Детальные правила переноса</li><li>Требования платёжного провайдера</li></ol></section>
    <section className="case-next"><p className="case-index">12 — Next steps</p><h2>Проверить правила → протестировать flow → запустить MVP → измерить эффект</h2><p>До запуска зафиксировать baseline и event analytics. Через 4–6 недель сравнить rental hours, conversion, self-service rate, ручные обращения и conflicts.</p><button className="light-button" onClick={() => onView("admin")}>Открыть операционную часть <ArrowRight/></button></section>
  </main>;
}

function TimelineRow({ label, meta, children }) { return <div className="timeline-row"><div className="timeline-label"><strong>{label}</strong><span>{meta}</span></div><div className="timeline-track">{children}</div></div>; }
function positionStyle(start, durationMinutes) { return { left:`${((toMinutes(start)-600)/720)*100}%`, width:`${(durationMinutes/720)*100}%` }; }
function endTime(booking) { const value=toMinutes(booking.start)+booking.duration*60; return `${String(Math.floor(value/60)).padStart(2,"0")}:${String(value%60).padStart(2,"0")}`; }

function AdminPage({ bookings, setBookings, blocks, setBlocks, onView }) {
  const [date,setDate]=useState("2026-08-23"), [dialog,setDialog]=useState(null), [selectedId,setSelectedId]=useState(null);
  const [manual,setManual]=useState({customer:"",phone:"",passengers:3,start:"19:00",duration:1});
  const [manualError,setManualError]=useState(""), [editError,setEditError]=useState("");
  const dayBookings=bookings.filter((booking)=>booking.date===date&&booking.status!=="Cancelled"), selected=bookings.find((booking)=>booking.id===selectedId);
  const addManualBooking=()=>{const allocation=allocateBooking({...manual,date,bookings,blocks});if(!allocation.available)return setManualError(allocation.reason);setBookings([...bookings,{id:`NV-${1900+bookings.length}`,date,start:manual.start,duration:manual.duration,passengers:manual.passengers,boatId:allocation.boat.id,instructorId:allocation.instructor?.id||null,customer:manual.customer||"Клиент у причала",phone:manual.phone||"+7 900 000-00-00",source:"Ручная",payment:"Не оплачено",status:"Confirmed"}]);setDialog(null);setManualError("");};
  const updateAssignment=(field,value)=>{const next={...selected,[field]:value||null};const error=validateReassignment({booking:next,boatId:next.boatId,instructorId:next.instructorId,bookings,blocks});if(error)return setEditError(error);setBookings(bookings.map((booking)=>booking.id===next.id?next:booking));setEditError("");};
  return <main className="admin-page"><aside className="admin-sidebar"><div className="admin-brand">NEVA <span>operations</span></div>{[[CalendarBlank,"Расписание"],[Boat,"Флот"],[Users,"Инструкторы"],[CreditCard,"Платежи"]].map(([Icon,label],i)=><button className={i===0?"active":""} key={label}><Icon/>{label}</button>)}<button onClick={()=>onView("instructor")}><Clock/>Вид инструктора</button><div className="admin-user"><span>ИП</span><div><strong>Ирина</strong><small>Владелица</small></div></div></aside><div className="admin-content">
    <div className="admin-top"><div><p className="eyebrow">Единый источник правды</p><h1>Расписание ресурсов</h1></div><div className="admin-actions"><button className="secondary-button" onClick={()=>setDialog("block")}><Wrench/> Блокировка ресурса</button><button className="primary-button" onClick={()=>setDialog("booking")}><Plus/> Добавить бронь вручную</button></div></div>
    <div className="admin-date-row"><select value={date} onChange={(e)=>setDate(e.target.value)}>{dateOptions.map((d)=><option value={d.value} key={d.value}>{d.label}</option>)}</select><div className="legend"><span className="online">Онлайн</span><span className="manual">Ручная</span><span className="block">Техблок</span><span className="buffer">Буфер 30 мин</span></div></div>
    <section className="schedule-card"><div className="time-axis"><div/>{Array.from({length:13},(_,i)=><span key={i}>{10+i}:00</span>)}</div><p className="resource-title">КАТЕРА</p>{boats.map((boat)=><TimelineRow key={boat.id} label={boat.name} meta={`до ${boat.capacity} · Demo`}>{dayBookings.filter((b)=>b.boatId===boat.id).map((booking)=><button key={booking.id} className={`timeline-booking ${booking.source==="Ручная"?"manual":"online"}`} style={positionStyle(booking.start,booking.duration*60)} onClick={()=>setSelectedId(booking.id)}><strong>{booking.start} · {booking.customer.split(" ")[0]}</strong><span>{booking.passengers} гост. · {booking.source}</span></button>)}{dayBookings.filter((b)=>b.boatId===boat.id).map((booking)=><span key={`${booking.id}-buffer`} className="timeline-buffer" style={positionStyle(endTime(booking),30)}>30</span>)}{blocks.filter((b)=>b.date===date&&b.boatId===boat.id).map((block)=><span key={block.id} className="timeline-block" style={positionStyle(block.start,toMinutes(block.end)-toMinutes(block.start))}><Wrench size={14}/>{block.reason}</span>)}</TimelineRow>)}<p className="resource-title">ИНСТРУКТОРЫ · ОГРАНИЧИВАЮЩИЙ РЕСУРС</p>{instructors.map((person)=>{const shift=shifts.find((s)=>s.date===date&&s.instructorId===person.id);return <TimelineRow key={person.id} label={person.name} meta={shift?`${shift.start}–${shift.end}`:"Нет смены"}>{shift&&<span className="shift-band" style={positionStyle(shift.start,toMinutes(shift.end)-toMinutes(shift.start))}>Смена</span>}{dayBookings.filter((b)=>b.instructorId===person.id).map((booking)=><button key={booking.id} className="instructor-booking" style={positionStyle(booking.start,booking.duration*60+30)} onClick={()=>setSelectedId(booking.id)}>{booking.start} · {booking.customer.split(" ")[0]}</button>)}</TimelineRow>})}</section>
    <div className="admin-lower"><section className="commitments"><div><p className="eyebrow">Брони, которые нужно учесть при составлении смен</p><h2>Future staffing commitments</h2></div>{bookings.filter((booking)=>!shifts.some((shift)=>shift.date===booking.date)&&booking.instructorId===null).map((booking)=><article key={booking.id}><div><strong>{shortDates[booking.date]} · {booking.start}–{endTime(booking)}</strong><span>{booking.customer} · {booking.passengers} гостей</span></div><b>Нужен 1 инструктор</b><em>Confirmed · instructor TBD</em></article>)}</section><section className="capacity-note"><ShieldCheck size={28}/><h3>Свободный катер ≠ доступный слот</h3><p>В 16:00 два инструктора заняты. Катер C физически свободен, но новый слот клиенту не показывается.</p></section></div>
  </div>
  {selected&&<aside className="booking-inspector"><button className="inspector-close" onClick={()=>setSelectedId(null)}><X/></button><p className="eyebrow">{selected.id}</p><h2>{selected.customer}</h2><p>{selected.phone}</p><div className="inspector-status"><span>{selected.status}</span><span>{selected.payment}</span></div><dl><div><dt>Дата и время</dt><dd>{shortDates[selected.date]} · {selected.start}</dd></div><div><dt>Гости</dt><dd>{selected.passengers}</dd></div><div><dt>Источник</dt><dd>{selected.source}</dd></div></dl><label>Катер<select value={selected.boatId} onChange={(e)=>updateAssignment("boatId",e.target.value)}>{boats.map((boat)=><option key={boat.id} value={boat.id}>{boat.name} · до {boat.capacity}</option>)}</select></label><label>Инструктор<select value={selected.instructorId||""} onChange={(e)=>updateAssignment("instructorId",e.target.value)}><option value="">TBD</option>{instructors.map((person)=><option key={person.id} value={person.id}>{person.name}</option>)}</select></label>{editError&&<p className="form-error"><Warning/>{editError}</p>}<button className="secondary-button" onClick={()=>setBookings(bookings.map((b)=>b.id===selected.id?{...b,status:"Cancelled"}:b))}>Отменить бронь</button></aside>}
  {dialog&&<div className="booking-overlay"><div className="admin-dialog"><button className="inspector-close" onClick={()=>setDialog(null)}><X/></button>{dialog==="booking"?<><p className="eyebrow">Все каналы · одно расписание</p><h2>Добавить бронь вручную</h2><div className="dialog-grid"><label>Клиент<input value={manual.customer} onChange={(e)=>setManual({...manual,customer:e.target.value})}/></label><label>Телефон<input value={manual.phone} onChange={(e)=>setManual({...manual,phone:e.target.value})}/></label><label>Пассажиры<input type="number" min="1" max="8" value={manual.passengers} onChange={(e)=>setManual({...manual,passengers:Number(e.target.value)})}/></label><label>Начало<input type="time" step="1800" value={manual.start} onChange={(e)=>setManual({...manual,start:e.target.value})}/></label><label>Длительность<select value={manual.duration} onChange={(e)=>setManual({...manual,duration:Number(e.target.value)})}>{durations.map((d)=><option key={d} value={d}>{d} ч</option>)}</select></label></div>{manualError&&<p className="form-error"><Warning/>{manualError}</p>}<button className="primary-button" onClick={addManualBooking}>Проверить и добавить</button></>:<><p className="eyebrow">Исключить ресурс из availability</p><h2>Блокировка катера</h2><div className="block-preview"><Boat/><div><strong>Катер A · 10:00–12:00</strong><span>Техническое обслуживание</span></div></div><p>Перед сохранением система покажет конфликт, если на ресурс уже назначена бронь.</p><button className="primary-button" onClick={()=>{setBlocks([...blocks,{id:`block-${blocks.length+1}`,date,boatId:"boat-a",start:"10:00",end:"12:00",reason:"Техническое обслуживание"}]);setDialog(null);}}>Сохранить demo-блокировку</button></>}</div></div>}
  </main>;
}

function InstructorPage({ bookings, onView }) {
  const trips=bookings.filter((booking)=>booking.date==="2026-08-23"&&booking.instructorId==="alexey"&&booking.status!=="Cancelled");
  return <main className="instructor-page"><header><button onClick={()=>onView("admin")}><ArrowLeft/></button><div><span>NEVA · ИНСТРУКТОР</span><strong>Моё расписание</strong></div><div className="avatar">А</div></header><section><p className="eyebrow">Сегодня · 23 августа</p><h1>Здравствуйте, Алексей</h1><div className="shift-summary"><Clock/><div><span>Ваша смена</span><strong>10:00–18:00</strong></div><b>{trips.length} поездки</b></div><div className="trip-list">{trips.map((trip)=><article key={trip.id}><time>{trip.start}<span>{endTime(trip)}</span></time><div><p>{trip.customer}</p><span>{trip.passengers} пассажиров</span><strong>{boats.find((boat)=>boat.id===trip.boatId)?.name}</strong></div><CheckCircle size={24}/></article>)}</div><div className="read-only-note"><ShieldCheck/><div><strong>Расписание только для просмотра</strong><p>Изменения вносит Ирина в едином календаре.</p></div></div></section></main>;
}

export function App() {
  const [view,setView]=useState("home"), [bookingOpen,setBookingOpen]=useState(false), [bookings,setBookings]=useState(initialBookings), [blocks,setBlocks]=useState(initialBlocks);
  const [draft,setDraft]=useState({passengers:4,date:"2026-08-24",duration:2,start:"12:00"});
  const navigate=(nextView,anchor)=>{setView(nextView);window.scrollTo({top:0,behavior:"smooth"});if(anchor)window.setTimeout(()=>document.getElementById(anchor)?.scrollIntoView({behavior:"smooth"}),50);};
  const confirmBooking=({name,phone,allocation,...bookingDraft})=>setBookings((items)=>[...items,{id:`NV-${1900+items.length}`,...bookingDraft,customer:name,phone,boatId:allocation.boat.id,instructorId:allocation.instructor?.id||null,source:"Онлайн",payment:"Частично оплачено",status:"Confirmed"}]);
  return <>{view!=="instructor"&&<Header view={view} onView={navigate} onBook={()=>setBookingOpen(true)}/>} {view==="home"&&<HomePage draft={draft} setDraft={setDraft} bookings={bookings} blocks={blocks} onBook={()=>setBookingOpen(true)}/>} {view==="case"&&<CasePage onView={navigate}/>} {view==="admin"&&<AdminPage bookings={bookings} setBookings={setBookings} blocks={blocks} setBlocks={setBlocks} onView={navigate}/>} {view==="instructor"&&<InstructorPage bookings={bookings} onView={navigate}/>} {bookingOpen&&<BookingFlow draft={draft} setDraft={setDraft} bookings={bookings} blocks={blocks} onClose={()=>setBookingOpen(false)} onConfirm={confirmBooking}/>}</>;
}
